# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "abfdd801293621c44deee52a2dd640fa"
name = "Top Notification Bar"
handle = "top-notification-bar"
application_url = "https://system-magic-mass-receives.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_themes"

[auth]
redirect_urls = [
  "https://system-magic-mass-receives.trycloudflare.com/auth/callback",
  "https://system-magic-mass-receives.trycloudflare.com/auth/shopify/callback",
  "https://system-magic-mass-receives.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
